import { useEffect, useState } from 'react';
import { Activity, AlertTriangle, ArrowUpRight, Boxes, ChevronRight, ClipboardList, Gauge, Layers3, LayoutGrid, Menu, PackageCheck, Radio, Send, Settings2, Truck, Wifi, X, Zap } from 'lucide-react';
import { events as seedEvents, warehouse } from './data';
import { useWarehouseState } from './hooks';
import { WarehouseScene as DetailedWarehouseScene } from './WarehouseScene';

const navItems = [['Operations', LayoutGrid], ['Orders', ClipboardList], ['Fleet health', Truck], ['Event stream', Radio], ['Analytics', Gauge]];
const statusColor = { FREE: '#708391', RESERVED: '#53a9ff', LOADING: '#20d3b2', FAULT: '#ff6879' };

function Sidebar({ open, onClose }) {
  return <aside className={`sidebar ${open ? 'open' : ''}`}>
    <div className="brand"><div className="brand-mark">W</div><div><strong>WIS</strong><span>Warehouse Integration<br />Simulator</span></div><button className="mobile-close" onClick={onClose}><X size={17} /></button></div>
    <div className="site-switcher"><span className="site-pip" /><div><small>ACTIVE SITE</small><strong>North Hall / Zone 01</strong></div><ChevronRight size={15} /></div>
    <nav>{navItems.map(([label, Icon], index) => <button className={index === 0 ? 'active' : ''} key={label}><Icon size={17} /><span>{label}</span>{index === 0 && <i />}</button>)}</nav>
    <div className="side-rule" /><div className="side-label">SYSTEMS</div>
    <button className="system-link"><Zap size={16} /><span>Integration health</span><b>98%</b></button>
    <button className="system-link"><Settings2 size={16} /><span>Commissioning</span><ChevronRight size={14} /></button>
    <div className="sidebar-bottom"><div className="system-status"><span /><div><strong>System online</strong><small>All services running</small></div></div><small className="build">WIS HMI / BUILD 2.0.0</small></div>
  </aside>;
}

function Topbar({ mode, setMode, connected, onMenu }) {
  const [now, setNow] = useState(new Date());
  useEffect(() => { const timer = setInterval(() => setNow(new Date()), 1000); return () => clearInterval(timer); }, []);
  return <header className="topbar"><button className="menu-button" onClick={onMenu}><Menu size={19} /></button><div className="mobile-title"><strong>WIS</strong><span>Digital Twin HMI</span></div><div className="top-title"><small>OPERATIONS CONTROL</small><strong>Digital Twin HMI</strong></div><div className="view-switcher"><button className={mode === '2d' ? 'selected' : ''} onClick={() => setMode('2d')}><LayoutGrid size={15} /> 2D Operations</button><button className={mode === '3d' ? 'selected' : ''} onClick={() => setMode('3d')}><Layers3 size={15} /> 3D Twin</button></div><div className="top-meta"><div className="clock"><Activity size={15} /><strong>{now.toLocaleTimeString('en-GB', { hour12: false })}</strong><small>13 SEP 2026</small></div><div className="weather"><span>16°</span><small>ANTWERP / CLEAR</small></div><div className="operator"><div>O</div><span>OPERATOR<br /><small>LOCAL SHIFT</small></span></div><span className={`live-state ${connected ? 'online' : ''}`}><i />{connected ? 'LIVE MQTT' : 'DEMO MODE'}</span></div></header>;
}

function Kpis({ robots, orders, connected }) {
  const moving = robots.filter((robot) => robot.state === 'MOVING').length;
  return <section className="kpis"><article><span className="kpi-icon teal"><Truck size={18} /></span><div><strong>{moving || 1}</strong><small>ACTIVE ROBOTS</small><em>{robots.length} fleet units</em></div><ArrowUpRight size={15} /></article><article><span className="kpi-icon blue"><Boxes size={18} /></span><div><strong>12</strong><small>PALLETS IN SYSTEM</small><em>+3 since 12:00</em></div><ArrowUpRight size={15} /></article><article><span className="kpi-icon amber"><ClipboardList size={18} /></span><div><strong>{orders.filter((order) => order.status !== 'Completed').length}</strong><small>OPEN ORDERS</small><em>{orders.filter((order) => order.status === 'Completed').length} completed today</em></div><ArrowUpRight size={15} /></article><article><span className="kpi-icon coral"><AlertTriangle size={18} /></span><div><strong>1</strong><small>ACTIVE ALARMS</small><em>Dock-4 sensor warning</em></div><ArrowUpRight size={15} /></article><article className="availability"><div className="availability-ring"><strong>{connected ? '98' : '—'}</strong><small>%</small></div><div><small>SYSTEM AVAILABILITY</small><strong>{connected ? 'MQTT CONNECTED' : 'AWAITING BROKER'}</strong><em>Last 24 hours</em></div></article></section>;
}

function Floor2D({ robots, selected, setSelected, sensorActive, equipment }) {
  const footprint = (x, z, width, depth) => ({ left: `${((x - width / 2 + warehouse.width / 2) / warehouse.width) * 100}%`, top: `${((z - depth / 2 + warehouse.depth / 2) / warehouse.depth) * 100}%`, width: `${(width / warehouse.width) * 100}%`, height: `${(depth / warehouse.depth) * 100}%` });
  const point = (x, z) => ({ left: `${((x + warehouse.width / 2) / warehouse.width) * 100}%`, top: `${((z + warehouse.depth / 2) / warehouse.depth) * 100}%` });
  const activeRobot = robots.find((robot) => robot.id === selected) || robots.find((robot) => robot.state === 'MOVING');
  const routePoints = activeRobot?.route?.map((routePoint) => `${routePoint.x + warehouse.width / 2},${routePoint.z + warehouse.depth / 2}`).join(' ');
    return <div className="floor-2d"><div className="floor-grid" /><div className="spatial-label spatial-support-label">SUPPORT</div><div className="spatial-support"><b>BREAK<br />ROOM</b><b>OFFICE</b><b>WAITING<br />AREA</b></div><div className="spatial-label spatial-storage-label">STORAGE / ASRS</div>{warehouse.racks.map((rack) => <button key={rack.id} className={`spatial-rack ${selected === `Rack-${rack.id}` ? 'selected' : ''}`} style={footprint(rack.x, rack.z, rack.w, rack.d)} onClick={() => setSelected(`Rack-${rack.id}`)}><span>{rack.id}</span><i><b style={{ width: `${rack.fill}%` }} /></i><small>{rack.fill}%</small></button>)}<div className="spatial-label spatial-flow-label">INTERNAL FLOW</div>{warehouse.conveyors.map((conveyor, index) => <div className={`spatial-conveyor ${equipment.Running ? 'running' : ''} ${equipment.Jam ? 'fault' : ''}`} style={footprint(conveyor.x, conveyor.z, conveyor.w, conveyor.d)} key={conveyor.id}><span>{conveyor.id.toUpperCase()} / {equipment.Jam ? 'JAM' : equipment.Running ? 'RUNNING' : 'STOPPED'}</span><i style={{ animationDelay: `${index * 0.3}s` }} /></div>)}<div className="spatial-pick"><PackageCheck size={15} /><span>PICK STATION 01</span><b>READY / 4 PALLETS</b></div><div className="spatial-label spatial-docks-label">RECEIVING / SHIPPING</div>{warehouse.docks.map((dock) => <button key={dock.id} className="spatial-dock" style={footprint(dock.x, dock.z, 2.4, 2.7)} onClick={() => setSelected(dock.id)}><span>{dock.id.replace('-', ' ')}</span><b style={{ color: statusColor[dock.state] }}>{dock.state}</b></button>)}{routePoints && <svg className="telemetry-route" viewBox={`0 0 ${warehouse.width} ${warehouse.depth}`} preserveAspectRatio="none"><polyline points={routePoints} /></svg>}<div className="route route-a" /><div className="route route-b" />{sensorActive && <div className="sensor-pulse" />}{robots.map((robot) => <button key={robot.id} className={`robot-2d ${selected === robot.id ? 'selected' : ''}`} style={{ ...point(robot.x, robot.z), '--robot-color': robot.color }} onClick={() => setSelected(robot.id)}><span className="robot-body"><i /><i /></span><strong>{robot.id}</strong><small>{robot.state}</small></button>)}<div className="north-marker">N <ChevronRight size={12} /></div></div>;
}


function Inspector({ selected, robots, setSelected }) { const robot = robots.find((item) => item.id === selected); const dock = warehouse.docks.find((item) => item.id === selected); const rack = warehouse.racks.find((item) => `Rack-${item.id}` === selected); return <aside className="inspector"><div className="panel-head"><div><small>LIVE INSPECTOR</small><h2>{robot?.id || dock?.id || (rack ? `Rack-${rack.id}` : 'Warehouse floor')}</h2></div><button onClick={() => setSelected('floor')}><X size={15} /></button></div>{robot ? <><div className="inspector-hero"><div className="robot-badge" style={{ '--badge-color': robot.color }}><Truck size={25} /></div><div><strong>Autonomous mobile robot</strong><small>{robot.lastSeen}</small></div><b className={robot.state === 'MOVING' ? 'is-moving' : ''}><i />{robot.state}</b></div><div className="inspect-rows"><div><span>Position</span><strong>X {robot.x.toFixed(1)} / Z {robot.z.toFixed(1)}</strong></div><div><span>Battery</span><strong>{robot.battery}% <i className="battery"><b style={{ width: `${robot.battery}%` }} /></i></strong></div><div><span>Current task</span><strong>{robot.task}</strong></div><div><span>Speed</span><strong>{robot.state === 'MOVING' ? '0.8 m/s' : '0.0 m/s'}</strong></div><div><span>Route</span><strong>Rack B → Sort → Dock 2</strong></div></div><button className="outline-button"><ArrowUpRight size={14} /> Focus route</button></> : <div className="floor-summary"><div className="summary-icon"><LayoutGrid size={23} /></div><strong>{dock ? `${dock.id} station` : rack ? `Rack ${rack.id} shelving` : 'North Hall / Zone 01'}</strong><p>{dock ? `Dock status is ${dock.state.toLowerCase()}. Sensor telemetry is being monitored.` : rack ? `${rack.fill}% occupied across three pallet levels at X ${rack.x.toFixed(1)} / Z ${rack.z.toFixed(1)}.` : 'Operational view of storage, picking, internal flow and outbound docks.'}</p><div className="summary-stat"><span>{rack ? 'RACK UTILIZATION' : 'FLOOR CAPACITY'}</span><b>{rack ? `${rack.fill}%` : '68%'}</b></div><div className="capacity"><i style={{ width: `${rack ? rack.fill : 68}%` }} /></div><div className="summary-stat"><span>NEXT SERVICE WINDOW</span><b>18:00</b></div></div>}<div className="inspector-events"><div className="panel-head"><small>RECENT EVENTS</small><Radio size={14} /></div>{seedEvents.slice(0, 3).map((event) => <p key={event.time}><time>{event.time}</time>{event.text}</p>)}</div></aside>; }

function EventRail({ events }) { return <section className="event-rail"><div className="panel-head"><div><small>MQTT EVENT STREAM</small><h2>Live events</h2></div><span className="stream-live"><i />LIVE</span></div><div className="event-list">{events.slice(0, 5).map((event, index) => <div className="event-row" key={`${event.time}-${index}`}><i /><div><strong>{event.topic}</strong><span>{event.text}</span></div><time>{event.time}</time></div>)}</div></section>; }
function Orders({ orders }) { return <section className="orders-panel"><div className="panel-head"><div><small>ORDER PROGRESS</small><h2>Outbound queue</h2></div><button>VIEW ALL <ChevronRight size={13} /></button></div>{orders.map((order) => <div className="order-row" key={order.id}><span className={`order-dot ${order.status === 'Completed' ? 'done' : ''}`} /><div><strong>{order.id}</strong><small>{order.customer} / {order.task}</small></div><b>{order.status}</b><div className="progress"><i style={{ width: `${order.progress}%` }} /></div><small>{order.progress}%</small></div>)}</section>; }
function Dispatch({ onDispatch, dispatching, dispatchMessage }) { return <section className="dispatch"><div className="panel-head"><div><small>COMMAND CONSOLE</small><h2>Dispatch order</h2></div><Send size={15} /></div><form onSubmit={onDispatch}><label>Customer<input name="customer" defaultValue="Toyota" required /></label><label>Dock<select name="dock" defaultValue="Dock-3"><option>Dock-1</option><option>Dock-2</option><option>Dock-3</option><option>Dock-4</option></select></label><label>SKU<select name="sku" defaultValue="P100"><option>P100</option><option>P200</option><option>P300</option></select></label><label>Qty<input name="qty" type="number" defaultValue="1" min="1" required /></label><button type="submit" disabled={dispatching}><Send size={14} /> {dispatching ? 'RELEASING...' : 'RELEASE ORDER'}</button></form>{dispatchMessage && <p className={`dispatch-message ${dispatchMessage.type}`}>{dispatchMessage.text}</p>}</section>; }

export default function App() {
  const { connected, robots, events, orders, sensorActive, equipment, setOrders } = useWarehouseState();
  const [mode, setMode] = useState('2d'); const [selected, setSelected] = useState('AMR-Ultra'); const [navOpen, setNavOpen] = useState(false); const [dispatching, setDispatching] = useState(false); const [dispatchMessage, setDispatchMessage] = useState(null);
  const handleDispatch = async (event) => { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const orderNumber = `ORD-${Date.now()}`; setDispatching(true); setDispatchMessage(null); try { const response = await fetch('http://localhost:8000/api/orders', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ order_number: orderNumber, customer: form.get('customer'), destination_dock: form.get('dock'), items: [{ product_sku: form.get('sku'), requested_qty: Number(form.get('qty')) }] }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.detail || 'ERP rejected the order'); setOrders((current) => [{ id: payload.order_number || orderNumber, customer: form.get('customer'), task: `${form.get('sku')} / ${form.get('qty')} units`, status: 'Pending', progress: 0 }, ...current]); setDispatchMessage({ type: 'success', text: `${payload.order_number || orderNumber} accepted by ERP and queued for WMS` }); formElement.reset(); } catch (error) { setDispatchMessage({ type: 'error', text: error.message || 'Dispatch failed' }); } finally { setDispatching(false); } };
    return <div className="app-shell"><Sidebar open={navOpen} onClose={() => setNavOpen(false)} /><div className="content"><Topbar mode={mode} setMode={setMode} connected={connected} onMenu={() => setNavOpen(true)} /><main><div className="crumb"><span>WAREHOUSE FLOOR</span><ChevronRight size={13} /><b>LIVE OPERATIONS</b><span className="health"><i /> SERVICES HEALTHY</span></div><Kpis robots={robots} orders={orders} connected={connected} /><div className="workspace-grid"><div className="primary-column"><section className="visual-panel"><div className="visual-head"><div><small>{mode === '2d' ? 'LIVE WAREHOUSE FLOOR' : 'IMMERSIVE DIGITAL TWIN'}</small><h1>North Hall <span>/ Zone 01</span></h1></div><div className="visual-tools"><span><i className="legend live" /> Robot telemetry</span><span><i className="legend amber" /> Dock activity</span><span className="scale">{mode === '2d' ? 'SCALE 1:100' : 'ORBIT / INSPECT'}</span></div></div><div className={`visual-canvas ${mode === '3d' ? 'canvas-3d' : ''}`}>{mode === '2d' ? <Floor2D robots={robots} selected={selected} setSelected={setSelected} sensorActive={sensorActive} equipment={equipment} /> : <DetailedWarehouseScene robots={robots} selected={selected} setSelected={setSelected} equipment={equipment} />}</div><div className="visual-footer"><span><i />Live positions are telemetry where available</span><span>{mode === '3d' ? 'Drag to orbit / scroll to zoom' : 'NORTH HALL / OPERATIONAL SCALE'}</span></div></section><div className="lower-grid"><EventRail events={events} /><Orders orders={orders} /></div></div><div className="right-column"><Inspector selected={selected} robots={robots} setSelected={setSelected} /><Dispatch onDispatch={handleDispatch} dispatching={dispatching} dispatchMessage={dispatchMessage} /></div></div></main><footer><span>WIS DIGITAL TWIN / LOCAL COMMISSIONING BUILD</span><span><Wifi size={12} /> {connected ? 'MQTT LIVE' : 'DEMO TELEMETRY'} <i /> {robots.length} FLEET UNITS</span></footer></div></div>;
}
